### ISSUE TITLE
is there a version for 1.19.2 [question]

### ISSUE THREAD

**Issue by xNasuni** [xpple/clientarguments#3]
i'm working on a mod and i happened to have to use a player for an argument and i found this, and i looked in the maven and the versions jump from 1.19 to 1.19.3 and i've tried 1.4.1 through 1.4.4 and none of them have worked for 1.19.2

**Comment by xNasuni** [comment]
i'm just gonna do 1.18.2 for now but yeah

**Comment by xpple** [comment]
Sorry for the late response, [release 1.4.1](https://github.com/xpple/clientarguments/releases/tag/v1.4.1) should work.
