### ISSUE TITLE
Backwards compatibility?

### ISSUE THREAD

**Issue by Kesuaheli** [xpple/clientarguments#5]
I there a way of getting older versions out of the maven repo?

I saw you updated it already to MC 1.20-rc1, or CArguments 1.5. Wich is cool, dont get me wrong! But I think it would be nice to have at least the last previous Minecraft version available. In this case MC 1.19.4, or CArguemts 1.4.4.

Or is there a deeper technical reason for why you removed them?

**Comment by xpple** [comment]
Well, as the subdomain was stupidly nuked, all of its files were deleted as well. I will rerun all the release actions, hopefully that will recover them. Sorry for all the inconveniences caused!

**Comment by Kesuaheli** [comment]
Oh well, I see 😆

**Comment by xpple** [comment]
It took some time, but all the previous versions are now back!
